"""C2's conflict_check reasoning gate (DR-043(e)(i), DR-044).

WHY THIS LIVES AT C2 AND NOT IN C3 -- the reasons, recorded in code because
they are the kind that get quietly reversed later:

  1. RETRIEVAL MACHINERY. The conflict check must read the corpus. The
     Chroma client, collection handling and DR-033's embedding-digest
     verification at store-open all live in C2 and were built in thread
     1.0.14. A model in C3 would need its own copy of all of it --
     duplicated code on the path where a silent failure (a corrupted or
     mismatched index) is hardest to detect.

  2. MODEL-SWAP RISK, STATED AS A RISK AND NOT A MEASUREMENT. Ollama
     reloads on a model change, observed in thread 1.0.15 when the context
     setting changed. If C3 and C2 called different models alternately on
     every turn, a reload per swap is plausible, and DR-017's kill switch
     is 8 s end to end. NOBODY HAS MEASURED TWO-MODEL ALTERNATION ON THIS
     BOX. This is a cheap risk to avoid, not a proven blocker.

  3. A CORRECTION THAT MUST NOT BE INHERITED. An earlier draft of this
     work justified the choice by claiming the UMA carve would not hold a
     second resident model. THAT CLAIM IS WRONG and must not be repeated
     in any DR or any comment. SEED §2 describes C3 as a tiny model that
     runs anywhere, including alongside another component, and this box
     ALREADY runs a second model (nomic-embed-text) for every retrieval
     call. No footprint measurement supports the carve claim. Recorded so
     the bad reasoning is not inherited by a later reader who finds the
     conclusion and assumes the argument was sound.

  4. REVERSIBILITY. This is reversible. What would make a C3-resident
     model feasible is giving C3 its own retrieval client -- a KNOWN COST,
     not a rewrite. Review trigger: if C3's policy logic ever needs to be
     model-driven rather than deterministic, or if the single-model
     serialisation at C2 becomes the T_ttfa bottleneck, reopen it and pay
     that cost.

THE PROMPT IS BIASED TOWARD NO-CONFLICT, DELIBERATELY. The known failure
of an instruction-tuned model asked "is there a tension here?" is
OVER-AGREEABLE INVENTION -- it will find one, because being helpful reads
as finding something. DR-043(e) puts the project's whole relocated noise
control on this gate, so a gate that always says yes is not a gate at all,
and DR-042's ceiling would then be the only thing left holding (which
silence satisfies trivially -- DR-042's own review trigger). Hence the
explicit instruction to answer NO CONFLICT unless the contradiction is
direct, and the requirement to quote the source line.

AUTHORITY IS NEVER GENERATED BY THE MODEL. The model may name a SOURCE; the
authority weight attached to that source is looked up from the retrieved
chunk's own tier metadata (`retrieval.AUTHORITY_BY_PATH`). DR-044 requires
Jester to state the authority of what it conflicts with, and a generated
authority claim would be exactly the confabulation DR-044 exists to avoid.
A SOURCE the model names that does not match any retrieved chunk is
REJECTED -- see `parse_conflict_reply`.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from .retrieval import (
    AUTHORITY_BY_PATH,
    AUTHORITY_PHRASE,
    AUTHORITY_UNLABELLED,
    RetrievalResult,
)

NO_CONFLICT = "NO CONFLICT"

# Kept small and rigid on purpose: a free-form answer would have to be
# parsed by heuristics, and a parse failure would silently become a
# no-conflict (or worse, a fabricated one).
CONFLICT_PROMPT_TEMPLATE = """You are checking a meeting transcript against a company's own documents.

Recent transcript:
{transcript}

The line to check:
{utterance}

Retrieved document extracts:
{evidence}

Does the line to check DIRECTLY contradict one of the retrieved extracts?

Answer NO CONFLICT unless there is a direct, specific contradiction that you
can point to in a named extract. Topical similarity is NOT a conflict. Two
documents discussing the same subject is NOT a conflict. Something merely
being unaddressed is NOT a conflict. If you are unsure, answer NO CONFLICT.

Reply in exactly one of these two forms and nothing else:

NO CONFLICT

or

CONFLICT: <one sentence: what was said, and what it contradicts>
SOURCE: <the exact source filename from the extract you used>
"""


@dataclass
class ConflictCandidate:
    """DR-044's structured record. NOT prose from the model.

    The fields are separate because the merge step (C3, DR-042(b)) composes
    a sentence from them -- and because DR-044's citation must reach speech
    as PROSE, not as a `[source #N]` bracket marker, which C4's text filter
    now strips. Handing C3 a pre-formatted string would put the bracket
    back in the only place it must not be.
    """

    utterance: str
    conflicts_with: str
    source: str
    authority: str = AUTHORITY_UNLABELLED
    tier: str = ""
    turn_id: str = ""

    @property
    def authority_phrase(self) -> str:
        return AUTHORITY_PHRASE.get(self.authority, AUTHORITY_PHRASE[AUTHORITY_UNLABELLED])

    def as_dict(self) -> dict:
        return {
            "utterance": self.utterance,
            "conflicts_with": self.conflicts_with,
            "source": self.source,
            "authority": self.authority,
            "tier": self.tier,
            "turn_id": self.turn_id,
        }


@dataclass
class ConflictCheckOutcome:
    """Either a candidate or an EXPLICIT no-conflict -- never None-as-maybe.

    `rejected_reason` carries why a model reply that looked like a conflict
    was discarded (an unmatched SOURCE, an unparseable reply). That is
    logged: a gate that silently drops malformed positives looks identical
    to a gate that is working, and DR-045 needs the difference visible.
    """

    conflict: bool
    candidate: ConflictCandidate | None = None
    raw_reply: str = ""
    rejected_reason: str = ""
    sources_offered: list[str] = field(default_factory=list)


def _source_authority_index(result: RetrievalResult) -> dict[str, tuple[str, str]]:
    """Map source_path -> (tier, authority) over everything retrieved.

    Built from the RETRIEVED CHUNKS, so authority can only ever be asserted
    for a document that actually came back from the store this turn.
    """
    index: dict[str, tuple[str, str]] = {}
    for path, chunks in result.by_path.items():
        authority = AUTHORITY_BY_PATH.get(path, AUTHORITY_UNLABELLED)
        for chunk in chunks:
            if chunk.source_path and chunk.source_path not in index:
                index[chunk.source_path] = (chunk.tier or path, authority)
    return index


def _match_source(named: str, index: dict[str, tuple[str, str]]) -> str | None:
    """Match the model's SOURCE line against a retrieved source path.

    Exact match first, then basename, then containment -- the model tends
    to shorten a path to its filename. Anything that matches nothing is a
    REJECT, not a fallback to 'unlabelled': an unmatched source means the
    model named a document it was not shown, which is the confabulation
    case, not a labelling gap.
    """
    named = named.strip().strip("[]<>\"'").strip()
    if not named:
        return None
    if named in index:
        return named
    for source in index:
        if source.rsplit("/", 1)[-1] == named.rsplit("/", 1)[-1]:
            return source
    for source in index:
        if named in source or source in named:
            return source
    return None


_CONFLICT_RE = re.compile(r"CONFLICT\s*:\s*(.+?)(?:\n|$)", re.IGNORECASE | re.DOTALL)
_SOURCE_RE = re.compile(r"SOURCE\s*:\s*(.+?)(?:\n|$)", re.IGNORECASE)


def parse_conflict_reply(
    reply: str, result: RetrievalResult, utterance: str, turn_id: str = ""
) -> ConflictCheckOutcome:
    """Parse the model's reply into an explicit outcome.

    EVERY ambiguous case resolves to no-conflict. That direction is chosen
    deliberately and is the same bias as the prompt: under DR-043(e) this
    gate is the noise control, so its failure mode should be silence, which
    DR-008 calls the product's value, rather than a spurious flag, which is
    the exact failure DR-008 measured.
    """
    index = _source_authority_index(result)
    offered = sorted(index)
    text = (reply or "").strip()

    if not text:
        return ConflictCheckOutcome(
            conflict=False, raw_reply=reply or "",
            rejected_reason="empty reply", sources_offered=offered,
        )

    normalized = " ".join(text.upper().split())
    # An explicit NO CONFLICT anywhere in a short reply wins over a
    # CONFLICT: line, so a model that hedges ("NO CONFLICT. Though
    # CONFLICT: ...") resolves to silence.
    if NO_CONFLICT in normalized:
        return ConflictCheckOutcome(
            conflict=False, raw_reply=text, sources_offered=offered
        )

    conflict_match = _CONFLICT_RE.search(text)
    if not conflict_match:
        return ConflictCheckOutcome(
            conflict=False, raw_reply=text,
            rejected_reason="reply matched neither form", sources_offered=offered,
        )

    statement = conflict_match.group(1).strip()
    # A CONFLICT: line whose body ran into the SOURCE: line (the token cap
    # can land mid-format) is trimmed rather than discarded.
    statement = _SOURCE_RE.split(statement)[0].strip().rstrip(".") or ""
    if not statement:
        return ConflictCheckOutcome(
            conflict=False, raw_reply=text,
            rejected_reason="empty conflict statement", sources_offered=offered,
        )

    source_match = _SOURCE_RE.search(text)
    if not source_match:
        return ConflictCheckOutcome(
            conflict=False, raw_reply=text,
            rejected_reason="conflict claimed with no SOURCE line",
            sources_offered=offered,
        )

    matched = _match_source(source_match.group(1), index)
    if matched is None:
        # DR-044's whole argument is that a stated conflict is CHECKABLE.
        # A conflict against a document that was never retrieved is not
        # checkable, and is the confabulation this gate must not pass.
        return ConflictCheckOutcome(
            conflict=False, raw_reply=text,
            rejected_reason=(
                f"named source {source_match.group(1).strip()!r} does not "
                f"match any retrieved chunk"
            ),
            sources_offered=offered,
        )

    tier, authority = index[matched]
    return ConflictCheckOutcome(
        conflict=True,
        candidate=ConflictCandidate(
            utterance=utterance,
            conflicts_with=statement,
            source=matched,
            authority=authority,
            tier=tier,
            turn_id=turn_id,
        ),
        raw_reply=text,
        sources_offered=offered,
    )


def build_conflict_prompt(transcript: str, utterance: str, evidence: str) -> str:
    return CONFLICT_PROMPT_TEMPLATE.format(
        transcript=transcript.strip() or "(nothing yet)",
        utterance=utterance.strip(),
        evidence=evidence.strip() or "(no documents retrieved)",
    )
